name: CI

on:
  push:
    branches: [ master, 3.x ]
  pull_request:
    branches: [ master, 3.x ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag zendesk_api_client_php-app

    - name: Run Composer install
      run: docker run --rm --volume "$(pwd):/app" zendesk_api_client_php-app make build

    - name: Run lint
      run: docker run --rm --volume "$(pwd):/app" zendesk_api_client_php-app make lint

    - name: Run tests
      run: docker run --rm --volume "$(pwd):/app" zendesk_api_client_php-app make test
